### ISSUE TITLE
Using it on which_is_the_fastest ?

### ISSUE THREAD

**Issue by waghanza** [tbrand/mssh#5]
Hi @tbrand,

As you know, I plan to cloudify `which_is_the_fastest`. 

For this, I have to execute sole task remotely (whithin SSH), do `mssh` could do this job for me.

I have not found, un `REAME` if we can specify a non-default SSH Key.

Is this feature actually available or planed ?

Regards,

**Comment by tbrand** [comment]
That's good! :+1:

Sorry for the missing documents. I don't have enough time for working on it now.

As you can see on https://github.com/tbrand/mssh/blob/master/spec/conf/user_and_key_for_group.yaml and https://github.com/tbrand/mssh/blob/master/spec/conf/user_and_key_for_node.yaml, you can specify another ssh key for a group or each node.

You can use `set` feature for the set of groups and jobs.

The sample configuration is like this.
```yaml
groups:

  - name: server
    nodes:
      - host: this.is.your.server.com
        user: username
        key: ~/aws_key.pem

  - name: client
    nodes:
      - host: this.is.your.client.com
        user: username
        key: ~/aws_key.pem

jobs:

  - name: exec-client
    commands:
      - your_client_command_here

  - name: exec-server
    commands:
      - your_server_command_here

set:

  - name: server
    jobs:
      - exec-server
    groups:
      - server

  - name: client
    jobs:
      - exec-client
    groups:
      - client
```

Then you can execute them like this.
```bash
mssh -c your_config.yaml -s server # exec server
mssh -c your_config.yaml -s client # exec client
```
